services:
  webapp:
    build: ./frontend

  api:
    container_name: backend-container
    build: ./api

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
