name: Stock Inventory CI

on:
  push:
    branches:
      - master 
      - develop

  pull_request:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: StockInventory
        ports:
          - 3306:3306

    env:
      HOST: ${{ vars.HOST }}
      USER: ${{ vars.USER }}
      DATABASE: ${{ vars.DATABASE }}
      JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: apps/api/package-lock.json

      - name: Use compatible npm version
        run: npm install --global npm@11.6.1
      - name: Install API Dependencies
        run: npm ci
      - name: Initialise test database
        run: mysql -h 127.0.0.1 -u ${{vars.USER }} -${{secrets.DB_PASSWORD}} StockInventory < database/DatabaseSetup.sql
      - name: Running Tests 
        run: npm test
      - run: npm run build

  frontend:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} 

    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Use compatible npm version
        run: npm install --global npm@11.6.1
      - name: Install API Dependencies
        run: npm ci
      - run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend

    env:
      DATABASE: ${{ vars.DATABASE }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose -f apps/docker-compose.yml config

      - name: Build Docker containers
        run: docker compose -f apps/docker-compose.yml build

      - name: Start containers
        run: docker compose -f apps/docker-compose.yml up -d

      - name: Check containers
        run: docker compose -f apps/docker-compose.yml ps

      - name: Stop containers
        if: always()
        run: docker compose -f apps/docker-compose.yml down